#!/usr/bin/env bash

echo 0 > /sys/kernel/debug/tracing/events/iaa_crypto/iaa_lat/enable
echo 0 > /sys/kernel/debug/tracing/events/zswap/iaa_lat/enable
echo 0 > /sys/kernel/debug/tracing/events/zswap/iaa_lat_len/enable
