#!/usr/bin/env bash

VERIFY=${1:-0}
DEBUG=${2:-0}

: ${by_n_threshold:=2048}

echo "DEBUG:"
echo $DEBUG
if [ $DEBUG -eq 1 ]
then
    echo -n 'module iaa_crypto +p' > /sys/kernel/debug/dynamic_debug/control
    echo -n 'module idxd +p' > /sys/kernel/debug/dynamic_debug/control
    echo "iaa_cryto,idxd dynamic_debug ENABLED"
else    
    echo -n 'module iaa_crypto -p' > /sys/kernel/debug/dynamic_debug/control
    echo -n 'module idxd -p' > /sys/kernel/debug/dynamic_debug/control
    echo "iaa_cryto,idxd dynamic_debug DISABLED"
fi

#
# enable iaa_crypto
#

echo "canned" > /sys/bus/dsa/drivers/crypto/compression_mode
echo "compression_mode:"
cat /sys/bus/dsa/drivers/crypto/compression_mode

echo async > /sys/bus/dsa/drivers/crypto/sync_mode
echo "sync_mode:"
cat /sys/bus/dsa/drivers/crypto/sync_mode

echo 2 > /sys/module/zswap/parameters/by_n
echo "by_n:"
cat /sys/module/zswap/parameters/by_n

echo "${by_n_threshold}" > /sys/module/zswap/parameters/by_n_threshold
echo "by_n_threshold:"
cat /sys/module/zswap/parameters/by_n_threshold

echo $VERIFY > /sys/bus/dsa/drivers/crypto/verify_compress
echo "verify_compress:"
cat /sys/bus/dsa/drivers/crypto/verify_compress

./setup_iaa_1wq_dedicated

#
# enable zswap
#
echo 0 > /sys/module/zswap/parameters/enabled

echo 50 > /sys/module/zswap/parameters/max_pool_percent
echo "zswap max_pool_percent:"
cat /sys/module/zswap/parameters/max_pool_percent

echo iaa_crypto > /sys/module/zswap/parameters/compressor
echo "zswap compressor:"
cat /sys/module/zswap/parameters/compressor

echo zsmalloc > /sys/module/zswap/parameters/zpool
echo "zswap zpool:"
cat /sys/module/zswap/parameters/zpool

echo 1 > /sys/module/zswap/parameters/enabled
echo "zswap enabled:"
cat /sys/module/zswap/parameters/enabled

echo 0 > /sys/module/zswap/parameters/same_filled_pages_enabled
echo "zswap same_filled_pages_enabled:"
cat /sys/module/zswap/parameters/same_filled_pages_enabled

#
# configure vm
#
echo 100 > /proc/sys/vm/swappiness
echo "vm swappiness:"
cat /proc/sys/vm/swappiness

echo never > /sys/kernel/mm/transparent_hugepage/enabled
echo "mm transparent_hugepage enabled:"
cat /sys/kernel/mm/transparent_hugepage/enabled

echo 1 > /proc/sys/vm/overcommit_memory
echo "vm overcommit_memory:"
cat /proc/sys/vm/overcommit_memory

grep -rH . /sys/module/iaa_crypto/parameters 2> /dev/null

dmesg -k | tail -n20

