#!/usr/bin/env bash
#
# disable zswap
#
#echo zbud > /sys/module/zswap/parameters/zpool
#echo iaa_crypto > /sys/module/zswap/parameters/compressor

echo lzo > /sys/module/zswap/parameters/compressor
swapoff -a

echo 0 > /sys/module/zswap/parameters/accept_threshold_percent
echo 0 > /sys/module/zswap/parameters/max_pool_percent
echo 0 > /sys/module/zswap/parameters/enabled
echo 0 > /sys/module/zswap/parameters/enabled

#
# disable iaa_crypto
#

./teardown_iaa_3wq

swapon -a
swapon --show


