#ifndef _SDSI_GENL_H
#define _SDSI_GENL_H

#define SDSI_GENL_NAME_LENGTH		32
#define SDSI_GENL_FAMILY_NAME		"intel-sdsi"
#define SDSI_GENL_VERSION		0x01

/* Attributes of sdsi_genl_family */
enum sdsi_genl_attr {
	SDSI_GENL_ATTR_UNSPEC,
	SDSI_GENL_ATTR_DEVS,
	SDSI_GENL_ATTR_DEV_ID,
	SDSI_GENL_ATTR_DEV_NAME,
	SDSI_GENL_ATTR_DEV_CERT,

	SDSI_GENL_ATTR_CERT_SLOT_NO,
	SDSI_GENL_ATTR_MEAS_SLOT_NO,
	SDSI_GENL_ATTR_SIGN_MEAS,
	SDSI_GENL_ATTR_MEASUREMENT,
	SDSI_GENL_ATTR_MEAS_TRANSCRIPT,
	SDSI_GENL_ATTR_MEAS_SIG,
	__SDSI_GENL_ATTR_MAX,
};
#define SDSI_GENL_ATTR_MAX (__SDSI_GENL_ATTR_MAX - 1)

enum sdsi_genl_cmd {
	SDSI_GENL_CMD_UNSPEC,
	SDSI_GENL_CMD_GET_DEVS,
	SDSI_GENL_CMD_AUTHORIZE,
	SDSI_GENL_CMD_GET_MEASUREMENTS,
	__SDSI_GENL_CMD_MAX,
};
#define SDSI_GENL_CMD_MAX (__SDSI_GENL_CMD_MAX - 1)

int sdsi_netlink_init(void);
int sdsi_netlink_exit(void);

#endif /* _SDSI_GENL_H */

