# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for linux/drivers/platform/x86/intel/pnp_excusion_monitor
#

obj-$(CONFIG_INTEL_TPMI_PEM)	:= intel_tpmi_pem.o
obj-$(CONFIG_INTEL_TPMI_PEM)	+= intel_tpmi_pem_core.o
